# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  url: <%= ENV["DATABASE_DEV_URL"] %>

production:
  primary: &primary_production
    <<: *default
    database: mmsite_prod_primary
    url: <%= ENV["DATABASE_PROD_URL"] %>
  cache:
    <<: *primary_production
    database: mmsite_prod_cache
    migrations_paths: db/cache_migrate
    url: <%= ENV["DATABASE_PROD_URL"] %>
  queue:
    <<: *primary_production
    database: mmsite_prod_queue
    migrations_paths: db/queue_migrate
    url: <%= ENV["DATABASE_PROD_URL"] %>
  cable:
    <<: *primary_production
    database: mmsite_prod_cable
    migrations_paths: db/cable_migrate
    url: <%= ENV["DATABASE_PROD_URL"] %>